match:
  video_path_0: C:/Users/yuboh/GitHub/data/RecSync0/VID/VID_20250625_084506.mp4
  video_path_1: C:/Users/yuboh/GitHub/data/RecSync1/VID/VID_20250625_084507.mp4

#  video_path_0: C:/Users/yuboh/GitHub/data/RecSync0/VID/VID_20250624_125441.mp4
#  video_path_1: C:/Users/yuboh/GitHub/data/RecSync1/VID/VID_20250624_125443.mp4

  threshold: "5ms"  # human-readable format: ns, us, ms, s supported
  visualize: true

stitch:
  root: output/exp/VID_20250624_125441
  threshold: "5ms"  # human-readable format: ns, us, ms, s supported
  left_subdir: "0"
  right_subdir: "1"

